import react from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import Task from './Task'
export default function Home () {
  let [ val, setValue ] = useState( '' )
  let [ taskList, setTaskList ] = useState( Task.getAll() )


  // function getTaskList () {

  //   let taskList = typeof window === 'undefined'
  //      ? []
  //      : JSON.parse( localStorage.getItem( "taskList" ) ) || []
  //    return taskList
  //  }

  function addTask () {
    // let list = getTaskList()
    // let task = { text: val }
    // list.push( task )
    // localStorage.setItem( "taskList", JSON.stringify( list ) )

    Task.add( val )
    setValue( '' )
  }
  function deleteTask ( text ) {

    let list = getTaskList()
    let newList = list.filter( ( task ) => task.text !== text )
    // localStorage.setItem( "taskList", JSON.stringify( newList ) )

  }
  
  return (
    <div className={ styles.container }>
      <Head>
        <title>Fuck Stuff</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/dp.png" />
      </Head>

      <div className="container">


        <h2> To Do List </h2>

        <div className="add-task-container">
          <input value={ val } onChange={ ( e ) => setValue( e.target.value ) } /> <button onClick={ () => addTask() }> + </button>
        </div>

        <div className="task-list-container">
          { taskList &&
            taskList.map( ( task, i ) => {
            return <div key={ i }>
              <span> { task.text }</span>
              <button onClick={ () => deleteTask( task.text ) }> - </button>
            </div>  
          })
        }

            </div>

      </div>

      </div>
      )
}
