
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import Task from './Task'
import TaskComponent from '../components/TaskComponent'
import AddTaskBar from '../components/AddTaskBar'
import TaskList from '../components/TaskList'

export default function Home () {

  
  const [show,setShow] = useState(false)

  return (
    <div className={ styles.container }>
      <Head>
        <title>Fuck Stuff</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/dp.png" />
      </Head>

      <div className="container">
        <h2> To Do List </h2>

        <AddTaskBar />

        <button onClick={ () => setShow( !show ) }> {show ? "hide" : "show"} </button>
        <div className="task-list-container">
          <TaskList show={ show } />
        </div>

      </div>

    </div>
  )
}
