import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import { AddTaskBar, TaskList } from '../components'
import TaskDb from '../db/Task'

export default function Home() {

  const [ taskList, setTaskList ] = useState( [] )
  const [ show, setShow ] = useState( false )

  const refreshTaskList = () => {
    setTaskList( TaskDb.getAll() )
  }

  useEffect( () => {
    let mounted = true

    if ( mounted ) {
      setTaskList( TaskDb.getAll() )
    }

    return () => { mounted = false }
  }, [] )

  return (
    <div className={ styles.container }>
      <Head>
        <title>Fuck Stuff</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/dp.png" />
        <script defer src="" />
      </Head>

      <div className="container">

        <div className="todo-header-container">
          <h2 className="todo-header"> To Do List </h2>
        </div>

        <div className="add-task-container">
          <AddTaskBar refreshTaskListFn={ refreshTaskList } />
        </div>

        <div className="task-list-container">
          <TaskList
            show={ show }
            refreshTaskListFn={ refreshTaskList }
            taskList={ taskList }
          />
        </div>

      </div>

    </div>
  )
}

